### ISSUE TITLE
PHP Warning on admin-ajax.php

### ISSUE THREAD

**Issue by rickalee** [10up/10up-experience#24] opened 2018-08-08 20:31 UTC
**E_WARNING: Invalid argument supplied for foreach()**
in remove_menu_page called at wp-content/plugins/10up-experience/includes/plugins.php (32)

I believe this is due to admin_init hook on https://github.com/10up/10up-experience/blob/develop/includes/plugins.php#L31

**Comment by helen** [comment] 2018-08-17 00:32
@rickalee I haven't been able to reproduce this - could you give me some specific steps I could follow so I can make sure my imagined fix will work? I 100% believe you, looking at the code, and I believe changing to the `admin_menu` hook instead would fix it.

**Comment by rickalee** [comment] 2018-08-17 15:32
@helen Found this in New Relic reports. Not replicated elsewhere. Will reach out to you via Slack with links due to confidentiality concerns.

**Comment by helen** [comment] 2018-08-20 19:49
Just making a note that the `admin_menu` hook doesn't fix this because of the way custom menu pages are added. Will have to look into another solution.

**Comment by ivanlopez** [comment] 2018-12-05 13:36
@rickalee @helen I'm also seeing this in New Relic. I'm happy to help debug and submit a PR.

**Comment by helen** [comment] 2018-12-05 14:43
@ivanlopez Yes please! cc @tlovett1

**Comment by ivanlopez** [comment] 2018-12-05 15:56
I've created a merge request that addresses this issue at #40

**Comment by claytoncollie** [comment] 2021-09-25 22:49
Can we close this issue now the PR has been merged?

cc @tlovett1 @ivanlopez

**Comment by darylldoyle** [comment] 2023-10-26 12:00
Closing as this was fixed

**Closed by darylldoyle** 2023-10-26 12:00 UTC
